### PR TITLE
Versions 1.2.12 + updates

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Ready to merge :)

**Comment by dbast** [comment]
@mariusvniekerk ping :)

**Comment by BastianZim** [comment]
@dbast Do you mind if I ping core on Gitter to have this merged? I’d also need it. :)

**Comment by BastianZim** [comment]
Thanks @mariusvniekerk!

**Pull request merged**
